function [freq, eps1, eps2] = importfile(filename)
%IMPORTFILE Import data from a text file
%  [FREQ, EPS1, EPS2] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [FREQ, EPS1, EPS2] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [freq, eps1, eps2] = importfile("C:\Users\705\Desktop\PMN_PSN\F\T_1.TXT", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 31-Jul-2024 15:00:00

%% Input handling

% If dataLines is not specified, define defaults

    dataLines = [5, Inf];


%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["freq", "eps1", "eps2", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9"];
opts.SelectedVariableNames = ["freq", "eps1", "eps2"];
opts.VariableTypes = ["double", "double", "double", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var4", "Var5", "Var6", "Var7", "Var8", "Var9"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var4", "Var5", "Var6", "Var7", "Var8", "Var9"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
freq = tbl.freq;
eps1 = tbl.eps1;
eps2 = tbl.eps2;
end